In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
b=np.array([[1,2,3],[3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [3]:
c=np.array([[1,2],[3,4],[4,5]])
print(c)

[[1 2]
 [3 4]
 [4 5]]


In [4]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
#np.arange
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
#np.ones and np.zeroes
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#np.random
np.random.random((3,4))

array([[0.96107798, 0.36329522, 0.55626705, 0.33749646],
       [0.65702646, 0.22301049, 0.78277293, 0.79820885],
       [0.0437421 , 0.97146785, 0.40947236, 0.13194762]])

In [15]:
#np.linspace
np.linspace(-5,10,10)

array([-5.        , -3.33333333, -1.66666667,  0.        ,  1.66666667,
        3.33333333,  5.        ,  6.66666667,  8.33333333, 10.        ])

In [16]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Array Attributes**

In [22]:
a1=np.arange(10)
a2=np.arange(12,dtype=int).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)


In [23]:
#ndim
a1.ndim

1

In [24]:
a2.ndim

2

In [25]:
a3.ndim

3

In [26]:
#shape
a1.shape

(10,)

In [27]:
a2.shape

(3, 4)

In [28]:
a3.shape

(2, 2, 2)

In [29]:
#size
a3.size

8

In [32]:
#itemsize
a3.itemsize

8

In [33]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int64
int64


**changing datatype**

In [34]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [35]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)


In [36]:
#scalar operations
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [37]:
 a2>10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
a1==2

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [44]:
#vector operations
a1**a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

**Array Functions**

In [45]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[41., 83., 20.],
       [89., 22., 76.],
       [17., 31.,  1.]])

In [47]:
#max/min/sum/prod
#0->col and 1->row
np.max(a1)

np.float64(89.0)

In [48]:
np.sum(a1)

np.float64(380.0)

In [49]:
np.prod(a1)

np.float64(5337388796960.0)

In [50]:
np.min(a1,axis=1)

array([20., 22.,  1.])

In [51]:
#mean/median/std/var
np.mean(a1)

np.float64(42.22222222222222)

In [52]:
#trignometric functions
np.sin(a1)

array([[-0.15862267,  0.96836446,  0.91294525],
       [ 0.86006941, -0.00885131,  0.56610764],
       [-0.96139749, -0.40403765,  0.84147098]])

In [53]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [54]:
 #log and exponenets
 np.log(a1)

array([[3.71357207, 4.41884061, 2.99573227],
       [4.48863637, 3.09104245, 4.33073334],
       [2.83321334, 3.4339872 , 0.        ]])

In [55]:
#round/floor/ceil
a4=np.random.random((2,3))*100

In [56]:
a4

array([[24.26022379, 11.52002297, 33.09265117],
       [82.65883674, 54.12546656,  7.29424211]])

In [57]:
np.ceil(a4)

array([[25., 12., 34.],
       [83., 55.,  8.]])

In [58]:
np.floor(a4)

array([[24., 11., 33.],
       [82., 54.,  7.]])

In [59]:
np.round(a4)

array([[24., 12., 33.],
       [83., 54.,  7.]])

**Indexing and Slicing**

In [60]:
a1=np.arange(10)
a2=np.arange(12,dtype=int).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)


In [61]:
a1[-1]

np.int64(9)

In [62]:
a2[1,0]

np.int64(4)

In [63]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
a3[1,0,0]

np.int64(4)

In [67]:
a1[2:5]

array([2, 3, 4])

In [69]:
a2[0,:]

array([0, 1, 2, 3])

In [70]:
a2[:,2]

array([ 2,  6, 10])

In [73]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [74]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [88]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [89]:
 for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [91]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [93]:
#transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [94]:
#ravel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [95]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [98]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [99]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [100]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [101]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]